use std::fmt;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};

use alacritty_terminal::event::{Event, EventListener};
use alacritty_terminal::grid::Dimensions;
use alacritty_terminal::term::{Config, Term};
use alacritty_terminal::vte::ansi::Processor;
use tokio::sync::{mpsc, watch};

use crate::dimensions::TerminalDimensions;
use crate::input::{SpecialKey, encode_special_key_for_mode};
use crate::snapshot::Snapshot;

/// The fixed byte stream used by the first native vertical slice.
///
/// It intentionally exercises ordinary text, SGR foreground/background/style
/// changes, cursor movement, wrapping, scrollback, CJK, combining marks, and
/// emoji. The renderer can later document or improve glyph support without
/// changing the terminal-state contract.
pub static FIXED_DEMO_BYTES: &[u8] = concat!(
    "\x1b[2J\x1b[H",
    "scrollback-history-01\r\n",
    "scrollback-history-02\r\n",
    "scrollback-history-03\r\n",
    "scrollback-history-04\r\n",
    "scrollback-history-05\r\n",
    "scrollback-history-06\r\n",
    "scrollback-history-07\r\n",
    "scrollback-history-08\r\n",
    "scrollback-history-09\r\n",
    "scrollback-history-10\r\n",
    "scrollback-history-11\r\n",
    "scrollback-history-12\r\n",
    "scrollback-history-13\r\n",
    "scrollback-history-14\r\n",
    "scrollback-history-15\r\n",
    "scrollback-history-16\r\n",
    "scrollback-history-17\r\n",
    "scrollback-history-18\r\n",
    "scrollback-history-19\r\n",
    "scrollback-history-20\r\n",
    "scrollback-history-21\r\n",
    "scrollback-history-22\r\n",
    "scrollback-history-23\r\n",
    "scrollback-history-24\r\n",
    "scrollback-history-25\r\n",
    "scrollback-history-26\r\n",
    "scrollback-history-27\r\n",
    "scrollback-history-28\r\n",
    "scrollback-history-29\r\n",
    "scrollback-history-30\r\n",
    "scrollback-history-31\r\n",
    "scrollback-history-32\r\n",
    "scrollback-history-33\r\n",
    "scrollback-history-34\r\n",
    "scrollback-history-35\r\n",
    "scrollback-history-36\r\n",
    "scrollback-history-37\r\n",
    "scrollback-history-38\r\n",
    "scrollback-history-39\r\n",
    "scrollback-history-40\r\n",
    "scrollback-history-41\r\n",
    "scrollback-history-42\r\n",
    "scrollback-history-43\r\n",
    "scrollback-history-44\r\n",
    "scrollback-history-45\r\n",
    "scrollback-history-46\r\n",
    "scrollback-history-47\r\n",
    "scrollback-history-48\r\n",
    "\x1b[2J\x1b[H",
    "meeterm native terminal demo\r\n",
    "ASCII: The quick brown fox jumps over the lazy dog.\r\n",
    "\x1b[1;31mANSI bold red\x1b[0m + ",
    "\x1b[4;38;5;45mindexed cyan underline\x1b[0m\r\n",
    "\x1b[30;47mblack on white\x1b[0m and ",
    "\x1b[44;97mbright white on blue\x1b[0m\r\n",
    "cursor: home\x1b[4Cmove\x1b[2Dok\r\n",
    "日本語 / CJK-ASCII: 日本語 ABC 123\r\n",
    "combining: e\u{301} cafe\u{301} / か\u{3099}\r\n",
    "emoji: 😀 🦊\r\n",
    "wrap: 0123456789 abcdefghijklmnopqrstuvwxyz ",
    "0123456789 abcdefghijklmnopqrstuvwxyz\r\n",
)
.as_bytes();

const MAX_COLUMNS: u16 = 4096;
const MAX_ROWS: u16 = 4096;
pub(crate) const MAX_INPUT_BYTES: usize = 64 * 1024;
pub(crate) const INPUT_QUEUE_CAPACITY: usize = 256;

/// The transport data plane is deliberately bounded.  Terminal event replies
/// (DA/DSR and similar responses generated by `alacritty_terminal`) use the
/// same queue as committed user input, so platform code never has to shuttle
/// terminal protocol bytes through JavaScript.
pub(crate) type InputSender = mpsc::Sender<Vec<u8>>;
pub(crate) type ResizeSender = watch::Sender<(u16, u16)>;

#[derive(Clone)]
pub(crate) struct TransportBinding {
    pub(crate) generation: u64,
    pub(crate) input: InputSender,
    pub(crate) resize: ResizeSender,
}

type TransportSlot = Arc<Mutex<Option<TransportBinding>>>;

#[derive(Clone)]
pub(crate) struct TerminalEventListener {
    outbound: TransportSlot,
    overloaded: Arc<AtomicBool>,
}

impl EventListener for TerminalEventListener {
    fn send_event(&self, event: Event) {
        let Event::PtyWrite(text) = event else {
            return;
        };

        let sender = self
            .outbound
            .lock()
            .ok()
            .and_then(|binding| binding.as_ref().map(|binding| binding.input.clone()));
        if let Some(sender) = sender {
            // EventListener is synchronous.  Never block the terminal mutex;
            // mark a full or closed queue so the SSH actor can fail the
            // transport instead of silently waiting for a lost reply.
            if sender.try_send(text.into_bytes()).is_err() {
                self.overloaded.store(true, Ordering::Release);
            }
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TerminalError {
    InvalidDimensions,
    InvalidUtf8,
    UnknownTerminal,
    RegistryPoisoned,
    SnapshotTooLarge,
    InputNotReady,
    InputQueueFull,
    TransportClosed,
    InputTooLarge,
    RemoteGenerationMismatch,
}

impl fmt::Display for TerminalError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidDimensions => formatter.write_str("terminal dimensions are invalid"),
            Self::InvalidUtf8 => formatter.write_str("input is not valid UTF-8"),
            Self::UnknownTerminal => formatter.write_str("terminal ID is not registered"),
            Self::RegistryPoisoned => formatter.write_str("terminal registry lock is poisoned"),
            Self::SnapshotTooLarge => formatter.write_str("snapshot exceeds the ABI size limit"),
            Self::InputNotReady => formatter.write_str("terminal connection is not ready"),
            Self::InputQueueFull => formatter.write_str("terminal input queue is full"),
            Self::TransportClosed => formatter.write_str("terminal transport is closed"),
            Self::InputTooLarge => formatter.write_str("terminal input is too large"),
            Self::RemoteGenerationMismatch => formatter.write_str("terminal connection is stale"),
        }
    }
}

impl std::error::Error for TerminalError {}

/// One Rust-owned terminal and its native-only input bookkeeping.
pub struct Terminal {
    term: Term<TerminalEventListener>,
    processor: Processor,
    input_commit_count: u64,
    content_revision: u64,
    remote_mode: bool,
    remote_generation: Option<u64>,
    transport_ready: bool,
    transport_overloaded: Arc<AtomicBool>,
    outbound: TransportSlot,
    #[cfg(test)]
    input_log: Vec<u8>,
}

impl Terminal {
    pub fn new(columns: u16, rows: u16) -> Result<Self, TerminalError> {
        validate_dimensions(columns, rows)?;

        let dimensions = TerminalDimensions {
            columns: usize::from(columns),
            screen_lines: usize::from(rows),
        };
        let outbound = Arc::new(Mutex::new(None));
        let transport_overloaded = Arc::new(AtomicBool::new(false));

        let mut terminal = Self {
            term: Term::new(
                terminal_config(),
                &dimensions,
                TerminalEventListener {
                    outbound: Arc::clone(&outbound),
                    overloaded: Arc::clone(&transport_overloaded),
                },
            ),
            processor: Processor::new(),
            input_commit_count: 0,
            content_revision: 0,
            remote_mode: false,
            remote_generation: None,
            transport_ready: false,
            transport_overloaded,
            outbound,
            #[cfg(test)]
            input_log: Vec::new(),
        };
        terminal.feed(FIXED_DEMO_BYTES);
        Ok(terminal)
    }

    /// Feed bytes from the native terminal data plane into `Term`.
    pub fn feed(&mut self, bytes: &[u8]) {
        if !bytes.is_empty() {
            self.content_revision = self.content_revision.saturating_add(1);
        }
        self.processor.advance(&mut self.term, bytes);
    }

    pub fn resize(&mut self, columns: u16, rows: u16) -> Result<(), TerminalError> {
        validate_dimensions(columns, rows)?;
        let changed = self.term.columns() != usize::from(columns)
            || self.term.screen_lines() != usize::from(rows);
        self.term.resize(TerminalDimensions {
            columns: usize::from(columns),
            screen_lines: usize::from(rows),
        });
        if changed {
            self.content_revision = self.content_revision.saturating_add(1);
        }

        if self.remote_mode {
            let resize_sender = self
                .outbound
                .lock()
                .ok()
                .and_then(|binding| binding.as_ref().map(|binding| binding.resize.clone()));
            if let Some(resize_sender) = resize_sender {
                // `watch` retains only the latest size and therefore naturally
                // coalesces rotations and pre-ready layout changes.
                let _ = resize_sender.send((columns, rows));
            }
        }
        Ok(())
    }

    /// Switch this terminal to the SSH data path.  Recreating the `Term`
    /// drops the built-in demo and scrollback, while `remote_mode` remains set
    /// for the lifetime of this terminal even if connection setup fails.
    pub(crate) fn begin_remote(&mut self, generation: u64) -> Result<(), TerminalError> {
        let columns =
            u16::try_from(self.term.columns()).map_err(|_| TerminalError::InvalidDimensions)?;
        let rows = u16::try_from(self.term.screen_lines())
            .map_err(|_| TerminalError::InvalidDimensions)?;
        validate_dimensions(columns, rows)?;

        if let Ok(mut binding) = self.outbound.lock() {
            *binding = None;
        }
        let dimensions = TerminalDimensions {
            columns: usize::from(columns),
            screen_lines: usize::from(rows),
        };
        self.term = Term::new(
            terminal_config(),
            &dimensions,
            TerminalEventListener {
                outbound: Arc::clone(&self.outbound),
                overloaded: Arc::clone(&self.transport_overloaded),
            },
        );
        self.processor = Processor::new();
        self.input_commit_count = 0;
        self.remote_mode = true;
        self.remote_generation = Some(generation);
        self.transport_ready = false;
        self.transport_overloaded.store(false, Ordering::Release);
        self.content_revision = self.content_revision.saturating_add(1);
        #[cfg(test)]
        self.input_log.clear();
        Ok(())
    }

    pub(crate) fn attach_transport(
        &mut self,
        generation: u64,
        input: InputSender,
        resize: ResizeSender,
    ) -> Result<(), TerminalError> {
        if !self.remote_mode || self.remote_generation != Some(generation) {
            return Err(TerminalError::RemoteGenerationMismatch);
        }
        let mut binding = self
            .outbound
            .lock()
            .map_err(|_| TerminalError::RegistryPoisoned)?;
        *binding = Some(TransportBinding {
            generation,
            input,
            resize,
        });
        self.transport_overloaded.store(false, Ordering::Release);
        Ok(())
    }

    pub(crate) fn detach_transport(&mut self, generation: u64) {
        if self.remote_generation != Some(generation) {
            return;
        }
        if let Ok(mut binding) = self.outbound.lock()
            && binding
                .as_ref()
                .is_some_and(|binding| binding.generation == generation)
        {
            *binding = None;
            self.transport_ready = false;
            self.transport_overloaded.store(false, Ordering::Release);
        }
    }

    pub(crate) fn mark_transport_ready(&mut self, generation: u64) -> bool {
        if self.remote_mode && self.remote_generation == Some(generation) {
            self.transport_ready = true;
            true
        } else {
            false
        }
    }

    pub(crate) fn feed_remote(&mut self, generation: u64, bytes: &[u8]) -> bool {
        if !self.remote_mode || self.remote_generation != Some(generation) {
            return false;
        }
        self.feed(bytes);
        !self.transport_overloaded.load(Ordering::Acquire)
    }

    pub(crate) fn transport_overloaded(&self) -> bool {
        self.transport_overloaded.load(Ordering::Acquire)
    }

    /// Commit already UTF-8 encoded text once.  Local terminals loop input
    /// back for the demo; SSH terminals enqueue it and wait for remote echo.
    pub fn commit_utf8(&mut self, bytes: &[u8]) -> Result<u64, TerminalError> {
        if bytes.is_empty() {
            return Ok(self.input_commit_count);
        }
        std::str::from_utf8(bytes).map_err(|_| TerminalError::InvalidUtf8)?;

        self.send_bytes(bytes)?;
        self.input_commit_count = self.input_commit_count.saturating_add(1);
        Ok(self.input_commit_count)
    }

    /// Send a special key through the current native transport.
    pub fn send_special_key(&mut self, key: SpecialKey) -> Result<usize, TerminalError> {
        let application_cursor = self
            .term
            .mode()
            .contains(alacritty_terminal::term::TermMode::APP_CURSOR);
        let bytes = encode_special_key_for_mode(key, application_cursor);
        self.send_bytes(bytes)
    }

    pub(crate) fn send_bytes(&mut self, bytes: &[u8]) -> Result<usize, TerminalError> {
        if bytes.is_empty() {
            return Ok(0);
        }
        if bytes.len() > MAX_INPUT_BYTES {
            return Err(TerminalError::InputTooLarge);
        }

        if self.remote_mode {
            if !self.transport_ready {
                return Err(TerminalError::InputNotReady);
            }
            let sender = self
                .outbound
                .lock()
                .map_err(|_| TerminalError::RegistryPoisoned)?
                .as_ref()
                .map(|binding| binding.input.clone())
                .ok_or(TerminalError::InputNotReady)?;
            sender
                .try_send(bytes.to_vec())
                .map_err(|error| match error {
                    mpsc::error::TrySendError::Full(_) => TerminalError::InputQueueFull,
                    mpsc::error::TrySendError::Closed(_) => TerminalError::TransportClosed,
                })?;
        } else {
            self.feed(bytes);
        }

        #[cfg(test)]
        self.input_log.extend_from_slice(bytes);
        Ok(bytes.len())
    }

    pub fn snapshot(&self) -> Result<Snapshot, TerminalError> {
        Snapshot::from_term(&self.term)
    }

    pub fn input_commit_count(&self) -> u64 {
        self.input_commit_count
    }

    pub(crate) fn content_revision(&self) -> u64 {
        self.content_revision
    }

    pub(crate) fn dimensions(&self) -> (u16, u16) {
        (
            u16::try_from(self.term.columns()).unwrap_or(MAX_COLUMNS),
            u16::try_from(self.term.screen_lines()).unwrap_or(MAX_ROWS),
        )
    }

    #[cfg(test)]
    pub(crate) fn input_log(&self) -> &[u8] {
        &self.input_log
    }

    #[cfg(test)]
    pub(crate) fn term(&self) -> &Term<TerminalEventListener> {
        &self.term
    }
}

fn terminal_config() -> Config {
    Config {
        scrolling_history: 256,
        ..Config::default()
    }
}

fn validate_dimensions(columns: u16, rows: u16) -> Result<(), TerminalError> {
    if columns < 2 || rows == 0 || columns > MAX_COLUMNS || rows > MAX_ROWS {
        return Err(TerminalError::InvalidDimensions);
    }
    Ok(())
}
