use std::fmt;
use std::sync::atomic::{AtomicBool, AtomicUsize, Ordering};
use std::sync::{Arc, Mutex};

use alacritty_terminal::event::{Event, EventListener};
use alacritty_terminal::grid::{Dimensions, Scroll};
use alacritty_terminal::index::{Column, Line, Point};
use alacritty_terminal::term::cell::Cell;
use alacritty_terminal::term::{Config, Term, TermMode, viewport_to_point};
use alacritty_terminal::vte::ansi::Processor;
use tokio::sync::{mpsc, watch};

use crate::dimensions::TerminalDimensions;
use crate::input::{
    KeyCode, Modifiers, SpecialKey, encode_key, encode_special_key_for_mode, encode_text,
};
use crate::snapshot::{Snapshot, Theme};

/// The fixed byte stream used by the first native vertical slice.
///
/// It intentionally exercises ordinary text, SGR foreground/background/style
/// changes, cursor movement, wrapping, scrollback, CJK, combining marks, and
/// emoji. The renderer can later document or improve glyph support without
/// changing the terminal-state contract.
pub static FIXED_DEMO_BYTES: &[u8] = concat!(
    "\x1b[2J\x1b[H",
    "scrollback-history-01\r\n",
    "scrollback-history-02\r\n",
    "scrollback-history-03\r\n",
    "scrollback-history-04\r\n",
    "scrollback-history-05\r\n",
    "scrollback-history-06\r\n",
    "scrollback-history-07\r\n",
    "scrollback-history-08\r\n",
    "scrollback-history-09\r\n",
    "scrollback-history-10\r\n",
    "scrollback-history-11\r\n",
    "scrollback-history-12\r\n",
    "scrollback-history-13\r\n",
    "scrollback-history-14\r\n",
    "scrollback-history-15\r\n",
    "scrollback-history-16\r\n",
    "scrollback-history-17\r\n",
    "scrollback-history-18\r\n",
    "scrollback-history-19\r\n",
    "scrollback-history-20\r\n",
    "scrollback-history-21\r\n",
    "scrollback-history-22\r\n",
    "scrollback-history-23\r\n",
    "scrollback-history-24\r\n",
    "scrollback-history-25\r\n",
    "scrollback-history-26\r\n",
    "scrollback-history-27\r\n",
    "scrollback-history-28\r\n",
    "scrollback-history-29\r\n",
    "scrollback-history-30\r\n",
    "scrollback-history-31\r\n",
    "scrollback-history-32\r\n",
    "scrollback-history-33\r\n",
    "scrollback-history-34\r\n",
    "scrollback-history-35\r\n",
    "scrollback-history-36\r\n",
    "scrollback-history-37\r\n",
    "scrollback-history-38\r\n",
    "scrollback-history-39\r\n",
    "scrollback-history-40\r\n",
    "scrollback-history-41\r\n",
    "scrollback-history-42\r\n",
    "scrollback-history-43\r\n",
    "scrollback-history-44\r\n",
    "scrollback-history-45\r\n",
    "scrollback-history-46\r\n",
    "scrollback-history-47\r\n",
    "scrollback-history-48\r\n",
    "\x1b[2J\x1b[H",
    "meeterm native terminal demo\r\n",
    "ASCII: The quick brown fox jumps over the lazy dog.\r\n",
    "\x1b[1;31mANSI bold red\x1b[0m + ",
    "\x1b[4;38;5;45mindexed cyan underline\x1b[0m\r\n",
    "\x1b[30;47mblack on white\x1b[0m and ",
    "\x1b[44;97mbright white on blue\x1b[0m\r\n",
    "cursor: home\x1b[4Cmove\x1b[2Dok\r\n",
    "日本語 / CJK-ASCII: 日本語 ABC 123\r\n",
    "combining: e\u{301} cafe\u{301} / か\u{3099}\r\n",
    "emoji: 😀 🦊\r\n",
    "wrap: 0123456789 abcdefghijklmnopqrstuvwxyz ",
    "0123456789 abcdefghijklmnopqrstuvwxyz\r\n",
)
.as_bytes();

const MAX_COLUMNS: u16 = 4096;
const MAX_ROWS: u16 = 4096;
pub const MIN_SCROLLBACK_LINES: usize = 1_000;
pub const MAX_SCROLLBACK_LINES: usize = 50_000;
pub const DEFAULT_SCROLLBACK_LINES: usize = 10_000;
pub(crate) const MAX_INPUT_BYTES: usize = 64 * 1024;
pub(crate) const INPUT_QUEUE_CAPACITY: usize = 256;

static SCROLLBACK_LINES: AtomicUsize = AtomicUsize::new(DEFAULT_SCROLLBACK_LINES);

pub fn configured_scrollback_lines() -> usize {
    SCROLLBACK_LINES.load(Ordering::Acquire)
}

pub fn validate_scrollback_lines(lines: usize) -> Result<(), TerminalError> {
    if (MIN_SCROLLBACK_LINES..=MAX_SCROLLBACK_LINES).contains(&lines) {
        Ok(())
    } else {
        Err(TerminalError::InvalidScrollbackLines)
    }
}

pub(crate) fn set_configured_scrollback_lines(lines: usize) -> Result<(), TerminalError> {
    validate_scrollback_lines(lines)?;
    SCROLLBACK_LINES.store(lines, Ordering::Release);
    Ok(())
}

/// The transport data plane is deliberately bounded.  Terminal event replies
/// (DA/DSR and similar responses generated by `alacritty_terminal`) use the
/// same queue as committed user input, so platform code never has to shuttle
/// terminal protocol bytes through JavaScript.
pub(crate) type InputSender = mpsc::Sender<Vec<u8>>;
pub(crate) type ResizeSender = watch::Sender<(u16, u16)>;

#[derive(Clone)]
pub(crate) struct TransportBinding {
    pub(crate) generation: u64,
    pub(crate) input: InputSender,
    pub(crate) resize: ResizeSender,
}

type TransportSlot = Arc<Mutex<Option<TransportBinding>>>;

#[derive(Clone)]
pub(crate) struct TerminalEventListener {
    outbound: TransportSlot,
    overloaded: Arc<AtomicBool>,
}

impl EventListener for TerminalEventListener {
    fn send_event(&self, event: Event) {
        let Event::PtyWrite(text) = event else {
            return;
        };

        let sender = self
            .outbound
            .lock()
            .ok()
            .and_then(|binding| binding.as_ref().map(|binding| binding.input.clone()));
        if let Some(sender) = sender {
            // EventListener is synchronous.  Never block the terminal mutex;
            // mark a full or closed queue so the SSH actor can fail the
            // transport instead of silently waiting for a lost reply.
            if sender.try_send(text.into_bytes()).is_err() {
                self.overloaded.store(true, Ordering::Release);
            }
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TerminalError {
    InvalidDimensions,
    InvalidUtf8,
    UnknownTerminal,
    RegistryPoisoned,
    SnapshotTooLarge,
    InvalidSelectionPoint,
    InvalidKey,
    InvalidModifiers,
    InvalidScrollbackLines,
    InputNotReady,
    InputQueueFull,
    TransportClosed,
    InputTooLarge,
    RemoteGenerationMismatch,
}

impl fmt::Display for TerminalError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidDimensions => formatter.write_str("terminal dimensions are invalid"),
            Self::InvalidUtf8 => formatter.write_str("input is not valid UTF-8"),
            Self::UnknownTerminal => formatter.write_str("terminal ID is not registered"),
            Self::RegistryPoisoned => formatter.write_str("terminal registry lock is poisoned"),
            Self::SnapshotTooLarge => formatter.write_str("snapshot exceeds the ABI size limit"),
            Self::InvalidSelectionPoint => {
                formatter.write_str("selection point is outside the viewport")
            }
            Self::InvalidKey => formatter.write_str("terminal key value is invalid"),
            Self::InvalidModifiers => formatter.write_str("input modifier bits are invalid"),
            Self::InvalidScrollbackLines => {
                formatter.write_str("scrollback lines are outside the supported bounds")
            }
            Self::InputNotReady => formatter.write_str("terminal connection is not ready"),
            Self::InputQueueFull => formatter.write_str("terminal input queue is full"),
            Self::TransportClosed => formatter.write_str("terminal transport is closed"),
            Self::InputTooLarge => formatter.write_str("terminal input is too large"),
            Self::RemoteGenerationMismatch => formatter.write_str("terminal connection is stale"),
        }
    }
}

impl std::error::Error for TerminalError {}

/// One Rust-owned terminal and its native-only input bookkeeping.
pub struct Terminal {
    term: Term<TerminalEventListener>,
    processor: Processor,
    theme: Theme,
    input_commit_count: u64,
    content_revision: u64,
    remote_mode: bool,
    remote_generation: Option<u64>,
    transport_ready: bool,
    transport_overloaded: Arc<AtomicBool>,
    outbound: TransportSlot,
    /// A generation change on an already remote terminal is a same-process
    /// reconnect. Its capture must replace only the viewport so the existing
    /// native scrollback is retained and the captured lines are not replayed
    /// into that history a second time.
    preserve_history_on_capture: bool,
    /// Whether at least one remote capture has populated the current native
    /// terminal. This distinguishes the first capture (which must replace the
    /// local/empty grid) from a later same-generation refresh, resize, or pane
    /// zoom. Those later captures must keep the history already owned by this
    /// `Term`, even when no reconnect generation changed.
    screen_initialized: bool,
    #[cfg(test)]
    input_log: Vec<u8>,
}

impl Terminal {
    pub fn new(columns: u16, rows: u16) -> Result<Self, TerminalError> {
        validate_dimensions(columns, rows)?;

        let dimensions = TerminalDimensions {
            columns: usize::from(columns),
            screen_lines: usize::from(rows),
        };
        let outbound = Arc::new(Mutex::new(None));
        let transport_overloaded = Arc::new(AtomicBool::new(false));

        let mut terminal = Self {
            term: Term::new(
                terminal_config(),
                &dimensions,
                TerminalEventListener {
                    outbound: Arc::clone(&outbound),
                    overloaded: Arc::clone(&transport_overloaded),
                },
            ),
            processor: Processor::new(),
            theme: Theme::Dark,
            input_commit_count: 0,
            content_revision: 0,
            remote_mode: false,
            remote_generation: None,
            transport_ready: false,
            transport_overloaded,
            outbound,
            preserve_history_on_capture: false,
            screen_initialized: false,
            #[cfg(test)]
            input_log: Vec::new(),
        };
        terminal.feed(FIXED_DEMO_BYTES);
        Ok(terminal)
    }

    /// Feed bytes from the native terminal data plane into `Term`.
    pub fn feed(&mut self, bytes: &[u8]) {
        if !bytes.is_empty() {
            self.content_revision = self.content_revision.saturating_add(1);
        }
        self.processor.advance(&mut self.term, bytes);
    }

    pub fn resize(&mut self, columns: u16, rows: u16) -> Result<(), TerminalError> {
        self.resize_inner(columns, rows, true)
    }

    pub(crate) fn resize_from_remote(
        &mut self,
        columns: u16,
        rows: u16,
    ) -> Result<(), TerminalError> {
        self.resize_inner(columns, rows, false)
    }

    fn resize_inner(&mut self, columns: u16, rows: u16, notify: bool) -> Result<(), TerminalError> {
        validate_dimensions(columns, rows)?;
        let changed = self.term.columns() != usize::from(columns)
            || self.term.screen_lines() != usize::from(rows);
        self.term.resize(TerminalDimensions {
            columns: usize::from(columns),
            screen_lines: usize::from(rows),
        });
        if changed {
            self.content_revision = self.content_revision.saturating_add(1);
        }

        if self.remote_mode && notify {
            let resize_sender = self
                .outbound
                .lock()
                .ok()
                .and_then(|binding| binding.as_ref().map(|binding| binding.resize.clone()));
            if let Some(resize_sender) = resize_sender {
                // `watch` retains only the latest size and therefore naturally
                // coalesces rotations and pre-ready layout changes.
                let _ = resize_sender.send((columns, rows));
            }
        }
        Ok(())
    }

    /// Switch this terminal to the SSH data path.
    ///
    /// The first transition replaces the local demo state. A later generation
    /// transition keeps the existing `Term` alive so same-process reconnects
    /// retain native scrollback; `restore_screen` then replaces only the
    /// captured viewport for that generation.
    pub(crate) fn begin_remote(&mut self, generation: u64) -> Result<(), TerminalError> {
        // A cancelled actor may still finish a synchronous registry operation
        // while its replacement starts. Never let it reset the newer terminal.
        if self
            .remote_generation
            .is_some_and(|current| generation < current)
        {
            return Err(TerminalError::RemoteGenerationMismatch);
        }
        let columns =
            u16::try_from(self.term.columns()).map_err(|_| TerminalError::InvalidDimensions)?;
        let rows = u16::try_from(self.term.screen_lines())
            .map_err(|_| TerminalError::InvalidDimensions)?;
        validate_dimensions(columns, rows)?;

        if let Ok(mut binding) = self.outbound.lock() {
            *binding = None;
        }
        let was_remote = self.remote_mode;
        let generation_changed = self.remote_generation != Some(generation);
        if !was_remote {
            self.replace_term(columns, rows);
            self.screen_initialized = false;
            self.preserve_history_on_capture = false;
        }
        self.processor = Processor::new();
        if !was_remote {
            self.input_commit_count = 0;
        }
        self.remote_mode = true;
        self.remote_generation = Some(generation);
        self.transport_ready = false;
        self.transport_overloaded.store(false, Ordering::Release);
        if generation_changed && was_remote {
            // A reconnect can arrive before its first capture. In that case
            // there is no native viewport/history to reconcile yet, so leave
            // the first capture on the full replacement path.
            self.preserve_history_on_capture = self.screen_initialized;
        }
        if !was_remote {
            self.content_revision = self.content_revision.saturating_add(1);
        }
        #[cfg(test)]
        if !was_remote {
            self.input_log.clear();
        }
        Ok(())
    }

    fn replace_term(&mut self, columns: u16, rows: u16) {
        let dimensions = TerminalDimensions {
            columns: usize::from(columns),
            screen_lines: usize::from(rows),
        };
        self.term = Term::new(
            terminal_config(),
            &dimensions,
            TerminalEventListener {
                outbound: Arc::clone(&self.outbound),
                overloaded: Arc::clone(&self.transport_overloaded),
            },
        );
        self.processor = Processor::new();
    }

    pub(crate) fn attach_transport(
        &mut self,
        generation: u64,
        input: InputSender,
        resize: ResizeSender,
    ) -> Result<(), TerminalError> {
        if !self.remote_mode || self.remote_generation != Some(generation) {
            return Err(TerminalError::RemoteGenerationMismatch);
        }
        let mut binding = self
            .outbound
            .lock()
            .map_err(|_| TerminalError::RegistryPoisoned)?;
        *binding = Some(TransportBinding {
            generation,
            input,
            resize,
        });
        self.transport_overloaded.store(false, Ordering::Release);
        Ok(())
    }

    pub(crate) fn restore_screen(
        &mut self,
        generation: u64,
        columns: u16,
        rows: u16,
        bytes: &[u8],
    ) -> Result<(), TerminalError> {
        if self.remote_generation != Some(generation) {
            return Err(TerminalError::RemoteGenerationMismatch);
        }
        let binding = self
            .outbound
            .lock()
            .map_err(|_| TerminalError::RegistryPoisoned)?
            .clone();
        let commits = self.input_commit_count;
        let transport_ready = self.transport_ready;
        let display_offset = self.term.grid().display_offset();
        let preserve_history = self.preserve_history_on_capture && self.screen_initialized;
        if preserve_history {
            self.restore_viewport_preserving_history(columns, rows, bytes, display_offset)?;
        } else {
            self.replace_term(columns, rows);
            self.remote_mode = true;
            self.remote_generation = Some(generation);
            self.resize_from_remote(columns, rows)?;
            self.feed(bytes);
            // A pane zoom/resize rebuilds its viewport from tmux. Retain the
            // reader's history position, bounded by the captured history.
            self.scroll_lines(i32::try_from(display_offset).unwrap_or(i32::MAX));
        }
        // From this point on the terminal owns a captured remote viewport.
        // Keep using the history-preserving path for every subsequent capture
        // in this process, including same-generation refreshes and resizes.
        self.screen_initialized = true;
        self.preserve_history_on_capture = true;
        self.input_commit_count = commits;
        *self
            .outbound
            .lock()
            .map_err(|_| TerminalError::RegistryPoisoned)? = binding;
        // Rebuilding a viewport must not reject live input while other panes
        // are still being captured. Initial/offline panes remain unready.
        self.transport_ready = transport_ready;
        Ok(())
    }

    /// Reconcile a same-process reconnect without replaying tmux's bounded
    /// capture into the existing scrollback. The capture contains history as
    /// well as the viewport; only its final visible rows are needed when the
    /// previous native `Term` is still present.
    fn restore_viewport_preserving_history(
        &mut self,
        columns: u16,
        rows: u16,
        bytes: &[u8],
        display_offset: usize,
    ) -> Result<(), TerminalError> {
        self.resize_from_remote(columns, rows)?;
        self.term.scroll_display(Scroll::Bottom);

        let capture_is_alt = bytes.starts_with(b"\x1b[?1049h");
        let currently_alt = self.term.mode().contains(TermMode::ALT_SCREEN);
        if currently_alt && !capture_is_alt {
            self.feed(b"\x1b[?1049l");
        } else if !currently_alt && capture_is_alt {
            self.feed(b"\x1b[?1049h");
        }

        // Capture metadata is appended after the physical rows, so it cannot
        // establish the modes that must be active while those rows are fed.
        // Put the parser in deterministic defaults first; the metadata suffix
        // below then overwrites the modes and cursor position that tmux did
        // capture. This also prevents a stale INSERT/ORIGIN/LINE_WRAP mode
        // from changing how the viewport text is laid out.
        self.feed(RECONCILE_CAPTURE_PREFIX);

        // Clear only the active viewport. The history rows remain untouched,
        // and feeding at the top of this blank viewport cannot duplicate the
        // captured history when the final `rows` lines are used below.
        let grid = self.term.grid_mut();
        grid.cursor.template = Cell::default();
        grid.cursor.charsets = Default::default();
        grid.cursor.point = Point::new(Line(0), Column(0));
        grid.cursor.input_needs_wrap = false;
        // No saved-cursor metadata is present in the control-mode capture.
        // Seed it from the deterministic cursor rather than retaining a
        // position/template from a previous generation or viewport.
        grid.saved_cursor = grid.cursor.clone();
        grid.reset_region(..);
        self.term.selection = None;

        let viewport = capture_viewport_tail(bytes, usize::from(rows));
        let viewport = viewport.strip_prefix(b"\x1b[?1049h").unwrap_or(viewport);
        self.feed(viewport);
        self.scroll_lines(i32::try_from(display_offset).unwrap_or(i32::MAX));
        Ok(())
    }

    pub(crate) fn detach_transport(&mut self, generation: u64) {
        if self.remote_generation != Some(generation) {
            return;
        }
        if let Ok(mut binding) = self.outbound.lock()
            && binding
                .as_ref()
                .is_some_and(|binding| binding.generation == generation)
        {
            *binding = None;
            self.transport_ready = false;
            self.transport_overloaded.store(false, Ordering::Release);
        }
    }

    pub(crate) fn mark_transport_ready(&mut self, generation: u64) -> bool {
        if self.remote_mode && self.remote_generation == Some(generation) {
            self.transport_ready = true;
            true
        } else {
            false
        }
    }

    pub(crate) fn feed_remote(&mut self, generation: u64, bytes: &[u8]) -> bool {
        if !self.remote_mode || self.remote_generation != Some(generation) {
            return false;
        }
        self.feed(bytes);
        !self.transport_overloaded.load(Ordering::Acquire)
    }

    #[cfg(test)]
    pub(crate) fn transport_overloaded(&self) -> bool {
        self.transport_overloaded.load(Ordering::Acquire)
    }

    /// Commit already UTF-8 encoded text once.  Local terminals loop input
    /// back for the demo; SSH terminals enqueue it and wait for remote echo.
    pub fn commit_utf8(&mut self, bytes: &[u8]) -> Result<u64, TerminalError> {
        if bytes.is_empty() {
            return Ok(self.input_commit_count);
        }
        std::str::from_utf8(bytes).map_err(|_| TerminalError::InvalidUtf8)?;

        self.send_bytes(bytes)?;
        self.input_commit_count = self.input_commit_count.saturating_add(1);
        Ok(self.input_commit_count)
    }

    /// Commit text with native Ctrl/Alt handling. IME composition remains
    /// entirely in the platform view until this method receives committed
    /// Unicode text.
    pub fn commit_modified_utf8(
        &mut self,
        bytes: &[u8],
        modifiers: Modifiers,
    ) -> Result<usize, TerminalError> {
        let text = std::str::from_utf8(bytes).map_err(|_| TerminalError::InvalidUtf8)?;
        let encoded = encode_text(text, modifiers);
        if encoded.len() > MAX_INPUT_BYTES {
            return Err(TerminalError::InputTooLarge);
        }
        if encoded.is_empty() {
            return Ok(0);
        }
        self.send_bytes(&encoded)?;
        self.input_commit_count = self.input_commit_count.saturating_add(1);
        Ok(encoded.len())
    }

    /// Paste is distinct from IME commitment. Strip terminal control characters
    /// that could escape a paste envelope; normalize newlines for terminal input.
    pub fn paste_utf8(&mut self, bytes: &[u8]) -> Result<usize, TerminalError> {
        let text = std::str::from_utf8(bytes).map_err(|_| TerminalError::InvalidUtf8)?;
        if bytes.len() > MAX_INPUT_BYTES {
            return Err(TerminalError::InputTooLarge);
        }
        let text = text.replace("\r\n", "\n").replace('\r', "\n");
        let text: String = text
            .chars()
            .filter(|c| !c.is_control() || *c == '\n' || *c == '\t')
            .collect();
        if text.is_empty() {
            return Ok(0);
        }
        let bytes = if self
            .term
            .mode()
            .contains(alacritty_terminal::term::TermMode::BRACKETED_PASTE)
        {
            format!("\x1b[200~{text}\x1b[201~").into_bytes()
        } else {
            text.replace('\n', "\r").into_bytes()
        };
        self.send_bytes(&bytes)
    }

    /// Move the native viewport, retaining an independent offset per pane.
    pub fn scroll_lines(&mut self, lines: i32) {
        let before = self.term.grid().display_offset();
        self.term
            .scroll_display(alacritty_terminal::grid::Scroll::Delta(
                lines.clamp(-10000, 10000),
            ));
        if self.term.grid().display_offset() != before {
            self.content_revision = self.content_revision.saturating_add(1);
        }
    }

    /// Send a special key through the current native transport.
    pub fn send_special_key(&mut self, key: SpecialKey) -> Result<usize, TerminalError> {
        let application_cursor = self
            .term
            .mode()
            .contains(alacritty_terminal::term::TermMode::APP_CURSOR);
        let bytes = encode_special_key_for_mode(key, application_cursor);
        self.send_bytes(bytes)
    }

    /// Send a generic key with Ctrl/Alt/Shift modifiers.
    pub fn send_key(&mut self, key: KeyCode, modifiers: Modifiers) -> Result<usize, TerminalError> {
        let application_cursor = self.term.mode().contains(TermMode::APP_CURSOR);
        let bytes = encode_key(key, modifiers, application_cursor);
        self.send_bytes(&bytes)
    }

    pub(crate) fn send_bytes(&mut self, bytes: &[u8]) -> Result<usize, TerminalError> {
        if bytes.is_empty() {
            return Ok(0);
        }
        if bytes.len() > MAX_INPUT_BYTES {
            return Err(TerminalError::InputTooLarge);
        }

        if self.remote_mode {
            if !self.transport_ready {
                return Err(TerminalError::InputNotReady);
            }
            let sender = self
                .outbound
                .lock()
                .map_err(|_| TerminalError::RegistryPoisoned)?
                .as_ref()
                .map(|binding| binding.input.clone())
                .ok_or(TerminalError::InputNotReady)?;
            sender
                .try_send(bytes.to_vec())
                .map_err(|error| match error {
                    mpsc::error::TrySendError::Full(_) => TerminalError::InputQueueFull,
                    mpsc::error::TrySendError::Closed(_) => TerminalError::TransportClosed,
                })?;
        } else {
            self.feed(bytes);
        }

        self.scroll_lines(i32::MIN);
        #[cfg(test)]
        self.input_log.extend_from_slice(bytes);
        Ok(bytes.len())
    }

    pub fn snapshot(&self) -> Result<Snapshot, TerminalError> {
        Snapshot::from_term_with_theme(&self.term, self.theme)
    }

    /// Start a simple native selection at a snapshot viewport coordinate.
    pub fn select_start(
        &mut self,
        viewport_row: u32,
        viewport_column: u32,
    ) -> Result<(), TerminalError> {
        let point = self.selection_point(viewport_row, viewport_column)?;
        self.term.selection = Some(alacritty_terminal::selection::Selection::new(
            alacritty_terminal::selection::SelectionType::Simple,
            point,
            alacritty_terminal::index::Side::Left,
        ));
        self.content_revision = self.content_revision.saturating_add(1);
        Ok(())
    }

    /// Extend the current native selection to a snapshot viewport coordinate.
    pub fn select_update(
        &mut self,
        viewport_row: u32,
        viewport_column: u32,
    ) -> Result<(), TerminalError> {
        let point = self.selection_point(viewport_row, viewport_column)?;
        let selection = self
            .term
            .selection
            .as_mut()
            .ok_or(TerminalError::InvalidSelectionPoint)?;
        selection.update(point, alacritty_terminal::index::Side::Right);
        self.content_revision = self.content_revision.saturating_add(1);
        Ok(())
    }

    pub fn clear_selection(&mut self) {
        if self.term.selection.take().is_some() {
            self.content_revision = self.content_revision.saturating_add(1);
        }
    }

    /// Return selected text to native clipboard code. This string never enters
    /// the React Native state or terminal snapshot data plane.
    pub fn selection_text(&self) -> Option<String> {
        self.term.selection_to_string()
    }

    pub fn set_theme(&mut self, light: bool) {
        let theme = if light { Theme::Light } else { Theme::Dark };
        if self.theme != theme {
            self.theme = theme;
            self.content_revision = self.content_revision.saturating_add(1);
        }
    }

    pub fn theme(&self) -> Theme {
        self.theme
    }

    pub(crate) fn apply_scrollback_limit(&mut self, lines: usize) -> Result<(), TerminalError> {
        validate_scrollback_lines(lines)?;
        self.term.set_options(Config {
            scrolling_history: lines,
            ..Config::default()
        });
        self.content_revision = self.content_revision.saturating_add(1);
        Ok(())
    }

    fn selection_point(
        &self,
        viewport_row: u32,
        viewport_column: u32,
    ) -> Result<Point, TerminalError> {
        let row =
            usize::try_from(viewport_row).map_err(|_| TerminalError::InvalidSelectionPoint)?;
        let column =
            usize::try_from(viewport_column).map_err(|_| TerminalError::InvalidSelectionPoint)?;
        if row >= self.term.screen_lines() || column >= self.term.columns() {
            return Err(TerminalError::InvalidSelectionPoint);
        }
        let mut point = viewport_to_point(
            self.term.grid().display_offset(),
            Point::new(row, Column(column)),
        );
        // A wide glyph's second cell is a spacer. Normalizing it to the
        // leading cell keeps both selection text and range highlighting
        // Unicode-safe. Combining marks already live on their leading cell.
        if self.term.grid()[point]
            .flags
            .contains(alacritty_terminal::term::cell::Flags::WIDE_CHAR_SPACER)
            && point.column.0 > 0
        {
            point.column -= 1;
        }
        Ok(point)
    }

    pub fn input_commit_count(&self) -> u64 {
        self.input_commit_count
    }

    pub(crate) fn content_revision(&self) -> u64 {
        self.content_revision
    }

    pub(crate) fn dimensions(&self) -> (u16, u16) {
        (
            u16::try_from(self.term.columns()).unwrap_or(MAX_COLUMNS),
            u16::try_from(self.term.screen_lines()).unwrap_or(MAX_ROWS),
        )
    }

    #[cfg(test)]
    pub(crate) fn input_log(&self) -> &[u8] {
        &self.input_log
    }

    #[cfg(test)]
    pub(crate) fn term(&self) -> &Term<TerminalEventListener> {
        &self.term
    }
}

fn terminal_config() -> Config {
    Config {
        scrolling_history: configured_scrollback_lines(),
        ..Config::default()
    }
}

/// Reset the terminal state that affects parsing captured rows. The suffix
/// produced by `capture-pane` restores the values it knows (insert, origin,
/// wrap, cursor visibility, application cursor, and bracketed paste) after the
/// rows. Modes without capture metadata use alacritty's normal defaults so a
/// stale remote application state cannot bleed into the next viewport.
const RECONCILE_CAPTURE_PREFIX: &[u8] = concat!(
    "\x1b[0m",     // SGR/cursor style
    "\x1b[4l",     // insert mode
    "\x1b[20l",    // line-feed/new-line mode
    "\x1b[?1l",    // application cursor
    "\x1b[?6l",    // origin mode
    "\x1b[?7h",    // line wrap (the default)
    "\x1b[?25l",   // cursor hidden until metadata is applied
    "\x1b[?1000l", // mouse click reporting
    "\x1b[?1002l", // mouse drag reporting
    "\x1b[?1003l", // mouse motion reporting
    "\x1b[?1004l", // focus reporting
    "\x1b[?1005l", // UTF-8 mouse encoding
    "\x1b[?1006l", // SGR mouse encoding
    "\x1b[?1007h", // alternate scroll (the default)
    "\x1b[?2004l", // bracketed paste
    "\x1b[r",      // full scrolling region and home cursor
    "\x1b>"        // normal keypad
)
.as_bytes();

/// Keep the capture's final visible rows when an existing native terminal is
/// being resynchronized. The control-mode capture is assembled as CRLF
/// separated physical lines followed by cursor/mode metadata; preserving the
/// final rows retains that metadata while excluding duplicate history lines.
fn capture_viewport_tail(bytes: &[u8], rows: usize) -> &[u8] {
    if rows == 0 {
        return &[];
    }
    let line_breaks = bytes
        .windows(2)
        .enumerate()
        .filter_map(|(index, pair)| (pair == b"\r\n").then_some(index))
        .collect::<Vec<_>>();
    let line_count = line_breaks.len().saturating_add(1);
    if line_count <= rows {
        return bytes;
    }
    let skip = line_count - rows;
    let start = line_breaks
        .get(skip.saturating_sub(1))
        .map_or(0, |index| index.saturating_add(2));
    &bytes[start..]
}

fn validate_dimensions(columns: u16, rows: u16) -> Result<(), TerminalError> {
    if columns < 2 || rows == 0 || columns > MAX_COLUMNS || rows > MAX_ROWS {
        return Err(TerminalError::InvalidDimensions);
    }
    Ok(())
}
